version: '3.9'
services:
  what-to-watch:
    image: mongo:4.4
    restart: always
    container_name: ${MONGO_DB_NAME}

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: what-to-watch

    ports:
      - ${MONGO_PORT}:27017

    volumes:
      - what-to-watch.mongo:/data/db

  what-to-watch.ui:
    image: mongo-express:latest
    restart: always
    container_name: what-to-watch.mongo.ui
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_DB_NAME}:${MONGO_PORT}/

volumes:
  what-to-watch.mongo:
