openapi: 3.1.0
info:
  title: API сервер для проекта «WHAT-TO-WATCH».
  description: |-
    * Список ресурсов и маршрутов сервера «WHAT-TO-WATCH».
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 2.0.0
