# Creating a new film
POST http://localhost:3000/film/ HTTP/1.1
Content-Type: application/json
Authorization:  Baerer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MjhhNzhlNTJjYzEwMTQ0MzQ5ODc0YSIsImVtYWlsIjoiU3ZldGFAbWFpbC5jb20iLCJuYW1lIjoiU3ZldGEiLCJpYXQiOjE3MzA4NzI3OTcsImV4cCI6MTczMDg3MjkxN30.qq2iSbk_RcYPe-AxJBZHmzWfQZZ5xFWURa_LYKCXXg0

{
  "nameFilm": "Зомби апакалипсис",
  "description": "Про парня попавшего в концлагерь.",
  "genres": "documentary",
  "release": "01.12.2024",
  "previewVideo": "https://www.youtube.com/preview/Бестрашный",
  "video": "https://www.youtube.com/video/Бестрашный",
  "actors": [
      "Влад",
      "Гера",
      "Злата"
      ],
  "director": "Макар",
  "movieDuration": "120 m",
  "poster": "Бестрашный.jpg",
  "backgroundImag": "Бестрашный.jpg",
  "backgroundColor": "gray"
}

###
# Film editing
PATCH http://localhost:3000/film/redaction/6729a4e3b3f173a2553497bf HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MjhhNzhlNTJjYzEwMTQ0MzQ5ODc0YSIsImVtYWlsIjoiU3ZldGFAbWFpbC5jb20iLCJuYW1lIjoiU3ZldGEiLCJpYXQiOjE3MzA3ODU3OTcsImV4cCI6MTczMDc4NTkxN30.AGmznFZ1umF9FAqab8TNY7bJ81mGKdghjVXXpp40E-A

{
  "promoFilm": true,
  "backgroundColor": "white"
}

###
## Deleting a movie
DELETE http://localhost:3000/film/6729a4e3b3f173a2553497bf HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MjhhNzhlNTJjYzEwMTQ0MzQ5ODc0YSIsImVtYWlsIjoiU3ZldGFAbWFpbC5jb20iLCJuYW1lIjoiU3ZldGEiLCJpYXQiOjE3MzA3ODU3OTcsImV4cCI6MTczMDc4NTkxN30.AGmznFZ1umF9FAqab8TNY7bJ81mGKdghjVXXpp40E-A

###
#Getting a list of movies
Get http://localhost:3000/film/list?limit=8 HTTP/1.1

###
# Getting a list of films of a certain genre
Get http://localhost:3000/film/list/genre?genre=ui&limit=3 HTTP/1.1

###
# Get detailed information on the film
GET http://localhost:3000/film/show/6729a4e3b3f173a2553497bf HTTP/1.1

###
# Get detailed information on the promo-film
GET http://localhost:3000/film/promo HTTP/1.1
