# Creating a new film
POST http://localhost:3000/film/ HTTP/1.1
Content-Type: application/json
Authorization:  Baerer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ODUzMGNiYWU2YWMyNDNlYzgwZTlmNCIsImVtYWlsIjoiVmxhZEBtYWlsLmNvbSIsIm5hbWUiOiJWbGFkIiwiYXZhdGFyIjoiaHR0cDovL2xvY2FsaG9zdDozMDAwL3N0YXRpYy9hdmF0YXIuanBnIiwiaWF0IjoxNzM3MzUyNTk2LCJleHAiOjE3MzczNTI3MTZ9.e9CwyUZiXy6MhJASJEutnKQs_CScrjMVFtjw7PVHCDo

{
  "nameFilm": "Красавчик",
  "description": "Про парня от которого женщины безума.",
  "genres": "documentary",
  "release": "01.12.2024",
  "previewVideo": "https://www.youtube.com/preview/Бестрашный",
  "video": "https://www.youtube.com/video/Бестрашный",
  "actors": [
      "Влад",
      "Гера",
      "Злата"
      ],
  "director": "Макар",
  "movieDuration": "120 m",
  "poster": "Бестрашный.jpg",
  "backgroundImag": "Бестрашный.jpg",
  "backgroundColor": "gray"
}

###
# Film editing
PATCH http://localhost:3000/film/redaction/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ODUzMGNiYWU2YWMyNDNlYzgwZTlmNCIsImVtYWlsIjoiVmxhZEBtYWlsLmNvbSIsIm5hbWUiOiJWbGFkIiwiYXZhdGFyIjoiaHR0cDovL2xvY2FsaG9zdDozMDAwL3N0YXRpYy9hdmF0YXIuanBnIiwiaWF0IjoxNzM3MjE1MDgxLCJleHAiOjE3MzcyMTUyMDF9.fdaN7UQXk-rF_UaFHZFpSPtuEDXQSXutmSEiyWvqTLA

{
  "promoFilm": false,
  "backgroundColor": "ggggggg",
  "actors": ["ghgh"]
}

###
## Deleting a movie
DELETE http://localhost:3000/film/4 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ODUzMGNiYWU2YWMyNDNlYzgwZTlmNCIsImVtYWlsIjoiVmxhZEBtYWlsLmNvbSIsIm5hbWUiOiJWbGFkIiwiYXZhdGFyIjoiaHR0cDovL2xvY2FsaG9zdDozMDAwL3N0YXRpYy9hdmF0YXIuanBnIiwiaWF0IjoxNzM3MzEwNTUyLCJleHAiOjE3MzczMTA2NzJ9.rkHl4EqcsSQqOanF6v8PRUqQtDSYKPEoOh0JRDliK_4

###
#Getting a list of movies
Get http://localhost:3000/film/list?limit=8 HTTP/1.1

###
# Getting a list of films of a certain genre
Get http://localhost:3000/film/list/genre?genre=drama&limit=3 HTTP/1.1

###
# Get detailed information on the film
GET http://localhost:3000/film/show/3 HTTP/1.1

###
# Get detailed information on the promo-film
GET http://localhost:3000/film/promo HTTP/1.1
