export * from './dto/create-film.dto.js';
export * from './dto/redaction-film.dto.js';
export * from './rdo/film.rdo.js';
export * from './rdo/full-information-film.rdo.js';
export * from './film.entity.js';
export * from './film.controller.js';
export * from './film.service.js';
export * from './film.repository.js';
export * from './film.container.js';
