# Creating a new comment
POST  http://localhost:3000/comment/ HTTP/1.1
Content-Type: application/json

{
  "rating": 10,
  "idFilm": "671f53e94f8b4282115477a2",
  "idUser": "671de33b79c27a5f656cd2ea"
}

###
# Getting a list of comments for a specific movie
GET   http://localhost:3000/comment/671f53e94f8b4282115477a2 HTTP/1.1
