# Creating a new comment
POST  http://localhost:3000/comment/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ODUzMGNiYWU2YWMyNDNlYzgwZTlmNCIsImVtYWlsIjoiVmxhZEBtYWlsLmNvbSIsIm5hbWUiOiJWbGFkIiwiYXZhdGFyIjoiaHR0cDovL2xvY2FsaG9zdDozMDAwL3N0YXRpYy9hdmF0YXIuanBnIiwiaWF0IjoxNzM3MzU3MDM3LCJleHAiOjE3MzczNTcxNTd9.3SIELqkqj3HgoReEYR3XBDGtQ1RvQopj_ZzKnk9TdkQ

{
  "rating": 10,
  "text": "Очень интересный фильм.",
  "idFilm": "3"
}

###
# Getting a list of comments for a specific movie
GET   http://localhost:3000/comment/67860617236e2ee56d9a9d7a HTTP/1.1
