# Creating a new comment
POST  http://localhost:3000/comment/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3N2Y5MzVlNzhjZjg3MDAwZGQwMmMyMCIsImVtYWlsIjoiVmxhZEBtYWlsLmNvbSIsIm5hbWUiOiJWbGFkIiwiaWF0IjoxNzM2NDE0OTA1LCJleHAiOjE3MzY0MTUwMjV9.R2FBrAEDA88VHQ-zcM8bIPd1b6xbx1WVSuLH6kh1P68

{
  "rating": 7,
  "text": "Очень интересный фильм. Рекомендую.",
  "idFilm": "677f93a278cf87000dd02c25"
}

###
# Getting a list of comments for a specific movie
GET   http://localhost:3000/comment/6729a4e3b3f173a2553497bf HTTP/1.1
