# Creating a new user
POST  http://localhost:3000/user/ HTTP/1.1
Content-Type: application/json

{
  "name": "Sveta",
  "email": "Sveta@mail.com",
  "avatar": "svets.jpg",
  "password": "4891SP"
}

###
# User authentication and authorization
GET   http://localhost:3000/user/login HTTP/1.1
Content-Type: application/json

{
  "email": "Sveta@mail.com",
  "password": "4891SP"
}

###
## User status check
GET   http://localhost:3000/user/authentication HTTP/1.1

###
## Отправить изображение
POST http://localhost:3000/user/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="avatar.jpg"
Content-Type: image/png

< C:\Users\User\Desktop\what-to-watch\markup\img\avatar.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--
